server:
  hostname: server-local
  port: 8097

# Application Log Properties
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{1.} %thread %msg%n"
  level:
    root: INFO
    br.com.example.spring.config: INFO
    br.com.example.spring: DEBUG

# Spring OpenAPI Properties
springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: br.com.spring_api.controller
  pathsToMatch: /api/**

# Spring Actuator
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring
    security:
      jwt:
        secret-key: 6F7A734F6762566A7134743777397A244326452948404D635166546A576E5A72
        expirationInMs: 2700000       # 45 minutes
        refreshExpirationInMs: 172800000 # 48 hours

  datasource:
    url: jdbc:h2:mem:springdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: true
